task_spec_version: '1.0'
id: django__django-11019
suite: swe-bench-lite-local
repo:
  url: https://github.com/django/django
  commit: 93e892bb645b16ebaf287beb5fe7f3ffe8d10408
environment:
  docker_image: ghcr.io/agentbench/py-runner:0.1.0
  workdir: /workspace
  timeout_sec: 180
setup:
  commands:
  - pip install --upgrade pip
  - pip install 'setuptools<69' wheel
  - pip install 'setuptools_scm>=6.2'
  - pip install 'oldest-supported-numpy' 'numpy<2'
  - pip install 'cython==0.29.22'
  - pip install extension-helpers
  - pip install pytest
  - pip install --no-build-isolation -e .
run:
  command: pytest -q test_combine_media (forms_tests.tests.test_media.FormsMediaTestCase)
    test_construction (forms_tests.tests.test_media.FormsMediaTestCase) test_form_media
    (forms_tests.tests.test_media.FormsMediaTestCase) test_media_deduplication (forms_tests.tests.test_media.FormsMediaTestCase)
    test_media_inheritance (forms_tests.tests.test_media.FormsMediaTestCase) test_media_inheritance_extends
    (forms_tests.tests.test_media.FormsMediaTestCase) test_media_property_parent_references
    (forms_tests.tests.test_media.FormsMediaTestCase) test_merge (forms_tests.tests.test_media.FormsMediaTestCase)
    test_merge_css_three_way (forms_tests.tests.test_media.FormsMediaTestCase) test_merge_js_three_way
    (forms_tests.tests.test_media.FormsMediaTestCase) test_merge_js_three_way2 (forms_tests.tests.test_media.FormsMediaTestCase)
    test_merge_warning (forms_tests.tests.test_media.FormsMediaTestCase) test_multi_widget
    (forms_tests.tests.test_media.FormsMediaTestCase) test_media (admin_widgets.test_autocomplete_widget.AutocompleteMixinTests)
    test_render_options (admin_widgets.test_autocomplete_widget.AutocompleteMixinTests)
    test_inline_media_only_inline (admin_inlines.tests.TestInlineMedia)
agent:
  entrypoint: llm_v0
  max_steps: 20
labels:
- swe-bench-lite
